import type { Podcast, Episode, Author } from '../types';

export const MOCK_PODCASTS: Podcast[] = [
  {
    id: 'p1',
    title: 'Tech Talk Daily',
    author: 'Sarah Johnson',
    description: 'Your daily dose of technology news, product reviews, and industry insights from Silicon Valley and beyond.',
    imageUrl: 'https://via.placeholder.com/300/4A90E2/ffffff?text=Tech+Talk',
    category: 'Technology',
    episodeCount: 342,
    rating: 4.8,
    latestEpisodeDate: '2026-01-30T10:00:00Z',
  },
  {
    id: 'p2',
    title: 'Comedy Hour with Mike',
    author: 'Mike Anderson',
    description: 'Stand-up comedy, hilarious stories, and interviews with the funniest people in entertainment.',
    imageUrl: 'https://via.placeholder.com/300/F5A623/ffffff?text=Comedy+Hour',
    category: 'Comedy',
    episodeCount: 198,
    rating: 4.6,
    latestEpisodeDate: '2026-01-29T18:00:00Z',
  },
  {
    id: 'p3',
    title: 'The Daily Brief',
    author: 'Emily Carter',
    description: 'Stay informed with comprehensive news coverage and deep-dive analysis of current events.',
    imageUrl: 'https://via.placeholder.com/300/E74C3C/ffffff?text=Daily+Brief',
    category: 'News',
    episodeCount: 521,
    rating: 4.9,
    latestEpisodeDate: '2026-02-01T06:00:00Z',
  },
  {
    id: 'p4',
    title: 'True Crime Chronicles',
    author: 'Detective James Reed',
    description: 'Investigating the most compelling true crime cases with expert analysis and exclusive interviews.',
    imageUrl: 'https://via.placeholder.com/300/8B4513/ffffff?text=True+Crime',
    category: 'True Crime',
    episodeCount: 156,
    rating: 4.7,
    latestEpisodeDate: '2026-01-28T20:00:00Z',
  },
  {
    id: 'p5',
    title: 'Learn Anything',
    author: 'Dr. Maria Rodriguez',
    description: 'Educational content covering science, history, philosophy, and everything in between.',
    imageUrl: 'https://via.placeholder.com/300/50C878/ffffff?text=Learn+Anything',
    category: 'Education',
    episodeCount: 289,
    rating: 4.9,
    latestEpisodeDate: '2026-01-31T12:00:00Z',
  },
  {
    id: 'p6',
    title: 'Business Builders',
    author: 'David Chen',
    description: 'Entrepreneurship, startup strategies, and interviews with successful business leaders.',
    imageUrl: 'https://via.placeholder.com/300/2E86AB/ffffff?text=Business',
    category: 'Business',
    episodeCount: 234,
    rating: 4.5,
    latestEpisodeDate: '2026-01-30T14:00:00Z',
  },
  {
    id: 'p7',
    title: 'AI Revolution',
    author: 'Sarah Johnson',
    description: 'Exploring artificial intelligence, machine learning, and the future of technology.',
    imageUrl: 'https://via.placeholder.com/300/9B59B6/ffffff?text=AI+Revolution',
    category: 'Technology',
    episodeCount: 87,
    rating: 4.8,
    latestEpisodeDate: '2026-01-31T09:00:00Z',
  },
  {
    id: 'p8',
    title: 'Startup Stories',
    author: 'David Chen',
    description: 'Real stories from founders who built successful companies from the ground up.',
    imageUrl: 'https://via.placeholder.com/300/E67E22/ffffff?text=Startups',
    category: 'Business',
    episodeCount: 145,
    rating: 4.7,
    latestEpisodeDate: '2026-01-29T15:00:00Z',
  },
  {
    id: 'p9',
    title: 'Mystery Solved',
    author: 'Detective James Reed',
    description: 'Cold cases, unsolved mysteries, and the investigators who never gave up.',
    imageUrl: 'https://via.placeholder.com/300/34495E/ffffff?text=Mystery',
    category: 'True Crime',
    episodeCount: 112,
    rating: 4.6,
    latestEpisodeDate: '2026-01-27T19:00:00Z',
  },
  {
    id: 'p10',
    title: 'Science Explained',
    author: 'Dr. Maria Rodriguez',
    description: 'Making complex scientific concepts accessible and entertaining for everyone.',
    imageUrl: 'https://via.placeholder.com/300/16A085/ffffff?text=Science',
    category: 'Education',
    episodeCount: 178,
    rating: 4.9,
    latestEpisodeDate: '2026-01-30T11:00:00Z',
  },
  {
    id: 'p11',
    title: 'Laugh Track',
    author: 'Mike Anderson',
    description: 'Improv comedy, sketches, and guest comedians bringing the laughs every week.',
    imageUrl: 'https://via.placeholder.com/300/F39C12/ffffff?text=Laugh',
    category: 'Comedy',
    episodeCount: 223,
    rating: 4.5,
    latestEpisodeDate: '2026-01-31T17:00:00Z',
  },
  {
    id: 'p12',
    title: 'World News Today',
    author: 'Emily Carter',
    description: 'International news coverage with correspondents reporting from around the globe.',
    imageUrl: 'https://via.placeholder.com/300/C0392B/ffffff?text=World+News',
    category: 'News',
    episodeCount: 412,
    rating: 4.8,
    latestEpisodeDate: '2026-02-01T07:00:00Z',
  },
  {
    id: 'p13',
    title: 'Code and Coffee',
    author: 'Alex Thompson',
    description: 'Programming tutorials, developer interviews, and software engineering best practices.',
    imageUrl: 'https://via.placeholder.com/300/27AE60/ffffff?text=Code',
    category: 'Technology',
    episodeCount: 167,
    rating: 4.7,
    latestEpisodeDate: '2026-01-31T08:00:00Z',
  },
  {
    id: 'p14',
    title: 'History Uncovered',
    author: 'Dr. Maria Rodriguez',
    description: 'Fascinating stories from history that shaped our world and changed everything.',
    imageUrl: 'https://via.placeholder.com/300/8E44AD/ffffff?text=History',
    category: 'Education',
    episodeCount: 201,
    rating: 4.8,
    latestEpisodeDate: '2026-01-29T13:00:00Z',
  },
  {
    id: 'p15',
    title: 'Entrepreneur Mindset',
    author: 'David Chen',
    description: 'Mental frameworks, productivity tips, and mindset strategies for business success.',
    imageUrl: 'https://via.placeholder.com/300/3498DB/ffffff?text=Mindset',
    category: 'Business',
    episodeCount: 189,
    rating: 4.6,
    latestEpisodeDate: '2026-01-30T16:00:00Z',
  },
  {
    id: 'p16',
    title: 'Comedy Central',
    author: 'Lisa Martinez',
    description: 'Stand-up sets, comedy writing, and interviews with rising comedy stars.',
    imageUrl: 'https://via.placeholder.com/300/E74C3C/ffffff?text=Central',
    category: 'Comedy',
    episodeCount: 134,
    rating: 4.7,
    latestEpisodeDate: '2026-01-31T19:00:00Z',
  },
  {
    id: 'p17',
    title: 'Breaking Headlines',
    author: 'Emily Carter',
    description: 'Real-time news analysis and investigative journalism on the stories that matter.',
    imageUrl: 'https://via.placeholder.com/300/95A5A6/ffffff?text=Breaking',
    category: 'News',
    episodeCount: 378,
    rating: 4.7,
    latestEpisodeDate: '2026-02-01T05:00:00Z',
  },
  {
    id: 'p18',
    title: 'Cyber Security Now',
    author: 'Alex Thompson',
    description: 'Protecting your digital life with the latest in cybersecurity news and advice.',
    imageUrl: 'https://via.placeholder.com/300/C0392B/ffffff?text=Security',
    category: 'Technology',
    episodeCount: 98,
    rating: 4.8,
    latestEpisodeDate: '2026-01-30T10:30:00Z',
  },
];

export const MOCK_EPISODES: Episode[] = [
  {
    id: 'e1',
    title: 'The Future of AI in Healthcare',
    podcastTitle: 'AI Revolution',
    podcastAuthor: 'Sarah Johnson',
    description: 'Exploring how artificial intelligence is transforming medical diagnosis and patient care.',
    duration: '45:23',
    releaseDate: '2026-01-31T09:00:00Z',
    episodeNumber: 87,
  },
  {
    id: 'e2',
    title: 'Building a Startup in 2026',
    podcastTitle: 'Startup Stories',
    podcastAuthor: 'David Chen',
    description: 'Interview with a founder who raised $10M Series A in just 6 months.',
    duration: '52:15',
    releaseDate: '2026-01-29T15:00:00Z',
    episodeNumber: 145,
  },
  {
    id: 'e3',
    title: 'The Missing Heiress Case',
    podcastTitle: 'Mystery Solved',
    podcastAuthor: 'Detective James Reed',
    description: 'How a 30-year-old cold case was finally solved using new DNA technology.',
    duration: '58:42',
    releaseDate: '2026-01-27T19:00:00Z',
    episodeNumber: 112,
  },
  {
    id: 'e4',
    title: 'Why Does the Sky Change Colors?',
    podcastTitle: 'Science Explained',
    podcastAuthor: 'Dr. Maria Rodriguez',
    description: 'The physics behind sunsets, sunrises, and atmospheric phenomena.',
    duration: '32:18',
    releaseDate: '2026-01-30T11:00:00Z',
    episodeNumber: 178,
  },
  {
    id: 'e5',
    title: 'Stand-Up Comedy Writing 101',
    podcastTitle: 'Laugh Track',
    podcastAuthor: 'Mike Anderson',
    description: 'Professional comedians share their secrets for writing killer jokes.',
    duration: '41:55',
    releaseDate: '2026-01-31T17:00:00Z',
    episodeNumber: 223,
  },
  {
    id: 'e6',
    title: 'Global Markets Update',
    podcastTitle: 'World News Today',
    podcastAuthor: 'Emily Carter',
    description: 'Analysis of major economic trends affecting markets worldwide.',
    duration: '28:30',
    releaseDate: '2026-02-01T07:00:00Z',
    episodeNumber: 412,
  },
  {
    id: 'e7',
    title: 'React 19 Deep Dive',
    podcastTitle: 'Code and Coffee',
    podcastAuthor: 'Alex Thompson',
    description: 'Exploring new features and breaking changes in the latest React release.',
    duration: '67:44',
    releaseDate: '2026-01-31T08:00:00Z',
    episodeNumber: 167,
  },
  {
    id: 'e8',
    title: 'The Fall of Rome',
    podcastTitle: 'History Uncovered',
    podcastAuthor: 'Dr. Maria Rodriguez',
    description: 'What really caused the collapse of the Roman Empire? New theories examined.',
    duration: '54:12',
    releaseDate: '2026-01-29T13:00:00Z',
    episodeNumber: 201,
  },
  {
    id: 'e9',
    title: 'Morning Routines of CEOs',
    podcastTitle: 'Entrepreneur Mindset',
    podcastAuthor: 'David Chen',
    description: 'How successful entrepreneurs structure their mornings for maximum productivity.',
    duration: '38:27',
    releaseDate: '2026-01-30T16:00:00Z',
    episodeNumber: 189,
  },
  {
    id: 'e10',
    title: 'Improv Games and Exercises',
    podcastTitle: 'Comedy Central',
    podcastAuthor: 'Lisa Martinez',
    description: 'Learn improv techniques used by professional comedy troupes.',
    duration: '44:15',
    releaseDate: '2026-01-31T19:00:00Z',
    episodeNumber: 134,
  },
  {
    id: 'e11',
    title: 'Election Coverage Special',
    podcastTitle: 'Breaking Headlines',
    podcastAuthor: 'Emily Carter',
    description: 'Live analysis and expert commentary on recent election results.',
    duration: '72:08',
    releaseDate: '2026-02-01T05:00:00Z',
    episodeNumber: 378,
  },
  {
    id: 'e12',
    title: 'Protecting Against Ransomware',
    podcastTitle: 'Cyber Security Now',
    podcastAuthor: 'Alex Thompson',
    description: 'Essential strategies to protect your business from ransomware attacks.',
    duration: '49:33',
    releaseDate: '2026-01-30T10:30:00Z',
    episodeNumber: 98,
  },
  {
    id: 'e13',
    title: 'Latest iPhone Features Reviewed',
    podcastTitle: 'Tech Talk Daily',
    podcastAuthor: 'Sarah Johnson',
    description: 'Hands-on review of the newest smartphone features and whether they\'re worth it.',
    duration: '36:45',
    releaseDate: '2026-01-30T10:00:00Z',
    episodeNumber: 342,
  },
  {
    id: 'e14',
    title: 'Funny Stories from the Road',
    podcastTitle: 'Comedy Hour with Mike',
    podcastAuthor: 'Mike Anderson',
    description: 'Hilarious behind-the-scenes stories from touring as a stand-up comedian.',
    duration: '55:20',
    releaseDate: '2026-01-29T18:00:00Z',
    episodeNumber: 198,
  },
  {
    id: 'e15',
    title: 'Climate Change Policy Update',
    podcastTitle: 'The Daily Brief',
    podcastAuthor: 'Emily Carter',
    description: 'New climate legislation and what it means for the future.',
    duration: '42:15',
    releaseDate: '2026-02-01T06:00:00Z',
    episodeNumber: 521,
  },
  {
    id: 'e16',
    title: 'The Serial Killer Next Door',
    podcastTitle: 'True Crime Chronicles',
    podcastAuthor: 'Detective James Reed',
    description: 'How a seemingly normal neighbor turned out to be a notorious criminal.',
    duration: '61:50',
    releaseDate: '2026-01-28T20:00:00Z',
    episodeNumber: 156,
  },
  {
    id: 'e17',
    title: 'Quantum Physics for Beginners',
    podcastTitle: 'Learn Anything',
    podcastAuthor: 'Dr. Maria Rodriguez',
    description: 'Breaking down quantum mechanics concepts in simple, understandable terms.',
    duration: '47:33',
    releaseDate: '2026-01-31T12:00:00Z',
    episodeNumber: 289,
  },
  {
    id: 'e18',
    title: 'Scaling Your Business',
    podcastTitle: 'Business Builders',
    podcastAuthor: 'David Chen',
    description: 'Strategies for growing from 10 to 100 employees without losing your culture.',
    duration: '50:12',
    releaseDate: '2026-01-30T14:00:00Z',
    episodeNumber: 234,
  },
  {
    id: 'e19',
    title: 'Machine Learning Basics',
    podcastTitle: 'AI Revolution',
    podcastAuthor: 'Sarah Johnson',
    description: 'Introduction to machine learning algorithms and practical applications.',
    duration: '43:28',
    releaseDate: '2026-01-24T09:00:00Z',
    episodeNumber: 86,
  },
  {
    id: 'e20',
    title: 'Failed Startups: Lessons Learned',
    podcastTitle: 'Startup Stories',
    podcastAuthor: 'David Chen',
    description: 'Founders share what went wrong and what they\'d do differently.',
    duration: '56:40',
    releaseDate: '2026-01-22T15:00:00Z',
    episodeNumber: 144,
  },
];

export const MOCK_AUTHORS: Author[] = [
  {
    id: 'a1',
    name: 'Sarah Johnson',
    bio: 'Technology journalist and podcast host with over 15 years of experience covering Silicon Valley.',
    imageUrl: 'https://via.placeholder.com/150/4A90E2/ffffff?text=SJ',
    podcastCount: 2,
    totalEpisodes: 429,
    genres: ['Technology', 'AI', 'Innovation'],
  },
  {
    id: 'a2',
    name: 'Mike Anderson',
    bio: 'Stand-up comedian and comedy writer. Former Saturday Night Live contributor.',
    imageUrl: 'https://via.placeholder.com/150/F5A623/ffffff?text=MA',
    podcastCount: 2,
    totalEpisodes: 421,
    genres: ['Comedy', 'Entertainment', 'Interviews'],
  },
  {
    id: 'a3',
    name: 'Emily Carter',
    bio: 'Award-winning journalist specializing in investigative reporting and political analysis.',
    imageUrl: 'https://via.placeholder.com/150/E74C3C/ffffff?text=EC',
    podcastCount: 3,
    totalEpisodes: 1311,
    genres: ['News', 'Politics', 'Current Events'],
  },
  {
    id: 'a4',
    name: 'Detective James Reed',
    bio: 'Retired homicide detective with 25 years of experience solving cold cases.',
    imageUrl: 'https://via.placeholder.com/150/8B4513/ffffff?text=JR',
    podcastCount: 2,
    totalEpisodes: 268,
    genres: ['True Crime', 'Investigation', 'Mystery'],
  },
  {
    id: 'a5',
    name: 'Dr. Maria Rodriguez',
    bio: 'PhD in Physics, science educator, and passionate about making science accessible to everyone.',
    imageUrl: 'https://via.placeholder.com/150/50C878/ffffff?text=MR',
    podcastCount: 3,
    totalEpisodes: 668,
    genres: ['Education', 'Science', 'History'],
  },
  {
    id: 'a6',
    name: 'David Chen',
    bio: 'Serial entrepreneur and venture capitalist. Founded 3 successful startups, now helping others.',
    imageUrl: 'https://via.placeholder.com/150/2E86AB/ffffff?text=DC',
    podcastCount: 3,
    totalEpisodes: 568,
    genres: ['Business', 'Entrepreneurship', 'Startups'],
  },
  {
    id: 'a7',
    name: 'Alex Thompson',
    bio: 'Software engineer and cybersecurity expert. Former Google senior developer.',
    imageUrl: 'https://via.placeholder.com/150/27AE60/ffffff?text=AT',
    podcastCount: 2,
    totalEpisodes: 265,
    genres: ['Technology', 'Programming', 'Security'],
  },
  {
    id: 'a8',
    name: 'Lisa Martinez',
    bio: 'Improv comedy teacher and performer. Trained at Second City and UCB.',
    imageUrl: 'https://via.placeholder.com/150/E67E22/ffffff?text=LM',
    podcastCount: 1,
    totalEpisodes: 134,
    genres: ['Comedy', 'Improv', 'Performance'],
  },
];
